Repository wecode-bootcamp-korea/41-1st-DCB-frontend, pull requests merged in 2023-01, with the labels that each got.

#2 [DCB] Add: icon pkg 설치
  package-lock.json
  package.json
Labels: 완료

#4 [41기 서지연] ADD: variables 파일 수정, stylelintrc 파일 selector class pattern 변경
  .stylelintrc.js
  src/styles/variables.scss
Labels: 완료

#3 [41기 이다혜] footer 레이아웃 구현
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterData.js
Labels: 멘토 리뷰 요청, merge 요청

#7 [41기 서지연] Add: Feature/item list/page 수정 사항 반영 완료
  public/data/selectedItems.json
  public/images/banner_1.jpg
  src/pages/ItemList/ItemList.js
  src/pages/ItemList/components/Product.js
  src/pages/ItemList/components/Products.js
  src/pages/ItemList/components/product.scss
  src/pages/ItemList/components/products.scss
  src/pages/ItemList/itemList.scss
Labels: 멘토 리뷰 요청, merge 요청

#5 [41기 서지연] Add: Feature/main 레이아웃 구현 완료 & Delete: item-list 컴포넌트 삭제
  public/data/products.json
  public/images/10.JPG
  public/images/11.JPG
  public/images/12.JPG
  public/images/13.JPG
  public/images/14.JPG
  public/images/15.JPG
  public/images/2.jpg
  public/images/4.jpg
  public/images/5.jpg
  public/images/8.jpeg
  public/images/banner.png
  public/images/선물.png
  src/pages/Main/Main.js
  src/pages/Main/components/EventImages.js
  src/pages/Main/components/ProductMain.js
  src/pages/Main/components/ProductsMain.js
  src/pages/Main/components/productMain.scss
  src/pages/Main/components/productsMain.scss
  src/pages/Main/main.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청, merge 요청

#16 [41기 이다혜] Feature/login/function 로그인 기능 구현 + Nav 오류 수정
  src/components/Nav/Nav.js
  src/pages/Login/Login.js
Labels: 멘토 리뷰 요청, merge 요청

#11 [41기 이다혜] Add: Feature/signup/page 레이아웃&기능구현
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
  src/pages/Signup/component/SignupData.js
  src/pages/Signup/component/UserInput.js
  src/pages/Signup/component/UserInput.scss
Labels: 멘토 리뷰 요청, merge 요청

#18 [41기 서지연] Modify: Update README.md
  README.md
Labels: 완료

#20 [41기 이다혜] Add: 카트 이미지에 장바구니 링크 추가 fix/nav/function
  src/components/Nav/Nav.js
Labels: 완료

#15 [41기 서지연] Add: Feature/main function
  src/Router.js
  src/config.js
  src/pages/ItemList/ItemList.js
  src/pages/ItemList/components/Product.js
  src/pages/Main/Main.js
  src/pages/Main/components/ProductMain.js
  src/pages/Main/components/ProductsMain.js
  src/pages/Main/components/productMain.scss
  src/pages/Main/components/productsMain.scss
  src/pages/Main/main.scss
Labels: 멘토 리뷰 요청, merge 요청

#17 [41기 서지연] Add: Feature/category
  src/components/Nav/Category.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/category.scss
Labels: 멘토 리뷰 요청, merge 요청

#24 [41기 이다혜] Feature/signup/function 회원가입 이용약관 동의 기능구현
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
  src/pages/Signup/component/SignupData.js
Labels: 멘토 리뷰 요청, merge 요청

#25 [41기 서지연] Add: Feature/scroll button 생성
  src/Router.js
  src/components/ScrollBtn/ScrollBtn.js
  src/components/ScrollBtn/scrollBtn.scss
Labels: 완료

#26 [41기 이다혜]Feature/mypage/page 마이페이지 레이아웃 구현
  src/Router.js
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/Mypage.scss
Labels: 멘토 리뷰 요청, merge 요청

#23 [41기 서지연] Add: Feature/search 검색기능 추가
  src/Router.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/ItemList/ItemList.js
  src/pages/Search/Search.js
  src/pages/Search/components/product.js
  src/pages/Search/components/product.scss
  src/pages/Search/components/products.js
  src/pages/Search/components/products.scss
  src/pages/Search/search.scss
Labels: 멘토 리뷰 요청, merge 요청

#19 [41기 서지연] Add: Feature/item list/function
  .env.sample
  .gitignore
  public/images/오른쪽.png
  public/images/왼쪽.png
  src/Router.js
  src/components/Nav/Category.js
  src/config.js
  src/pages/ItemList/ItemList.js
  src/pages/ItemList/components/Product.js
  src/pages/ItemList/components/Products.js
  src/pages/ItemList/components/product.scss
  src/pages/ItemList/components/products.scss
  src/pages/ItemList/itemList.scss
  src/pages/Login/Login.js
  src/pages/Main/Main.js
  src/pages/Main/components/ProductMain.js
  src/pages/Main/components/ProductsMain.js
  src/pages/Search/components/product.js
  src/pages/Signup/Signup.js
Labels: 멘토 리뷰 요청, merge 요청

#22 [41기 이다혜] Feature/navfunction 로그아웃 기능 & 반응형 nav바 구현
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavData.js
Labels: 멘토 리뷰 요청, merge 요청

#14 [41기 이세윤] ADD: Feature/cart/page 레이아웃&기능구현
  public/data/cartItems.json
  public/data/recommend.json
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/components/CartTotal/CartTotal.js
  src/pages/Cart/components/CartTotal/CartTotal.scss
  src/pages/Cart/components/ContentsContainer/ContentsCart/ContentsCart.js
  src/pages/Cart/components/ContentsContainer/ContentsCart/ContentsCart.scss
  src/pages/Cart/components/ContentsContainer/ContentsCart/components/CartItemWrap.js
  src/pages/Cart/components/ContentsContainer/ContentsCart/components/CartItemWrap.scss
  src/pages/Cart/components/ContentsContainer/ContentsCart/container/CartItemContainer.js
  src/pages/Cart/components/ContentsContainer/ContentsCart/container/CartItemContainer.scss
  src/pages/Cart/components/ContentsContainer/ContentsCart/container/SelectContainer.js
  src/pages/Cart/components/ContentsContainer/ContentsCart/container/SelectContainer.scss
  src/pages/Cart/components/ContentsContainer/ContentsContainer.js
  src/pages/Cart/components/ContentsContainer/ContentsContainer.scss
  src/pages/Cart/components/ContentsContainer/ContentsOrder/ContentsOrder.js
  src/pages/Cart/components/ContentsContainer/ContentsOrder/ContentsOrder.scss
Labels: 멘토 리뷰 요청, merge 요청

#10 [41기 장찬영] ADD: Feature/details
  public/data/details.json
  public/data/review.json
  public/data/reviewComments.json
  public/images/orora.png
  public/images/sample.jpg
  public/images/sample.png
  src/pages/Details/Detail.scss
  src/pages/Details/Details.js
  src/pages/Details/components/Comment.js
  src/pages/Details/components/Delivery.js
  src/pages/Details/components/Exchange.js
  src/pages/Details/components/MoreInformation.js
  src/pages/Details/components/Option.js
  src/pages/Details/components/Option.scss
  src/pages/Details/components/ProductDescription.js
  src/pages/Details/components/ProductDescription.scss
  src/pages/Details/components/Review.js
  src/pages/Details/components/Review.scss
  src/pages/Details/components/ReviewBottom.js
  src/pages/Details/components/ReviewBottom.scss
  src/pages/Details/components/TotalInfo.js
  src/pages/Details/components/TotalInfo.scss
Labels: 멘토 리뷰 요청, merge 요청

#27 [41기 이세윤] ADD: Feature/cart/page 레이아웃&기능구현
  public/data/recommend.json
  src/pages/Cart/Cart.js
  src/pages/Cart/components/CartTotal/CartTotal.js
  src/pages/Cart/components/ContentsContainer/ContentsCart/ContentsCart.scss
  src/pages/Cart/components/ContentsContainer/ContentsCart/components/CartItemWrap.js
  src/pages/Cart/components/ContentsContainer/ContentsCart/components/CartItemWrap.scss
  src/pages/Cart/components/ContentsContainer/ContentsCart/container/CartItemContainer.js
  src/pages/Cart/components/ContentsContainer/ContentsCart/container/SelectContainer.js
  src/pages/Cart/components/ContentsContainer/ContentsContainer.js
  src/pages/Cart/components/ContentsContainer/ContentsContainer.scss
  src/pages/Cart/components/ContentsContainer/RecommendItem.js
  src/pages/Cart/components/ContentsContainer/RecommendItem.scss
Labels: 멘토 리뷰 요청, merge 요청

#29 [41기 이세윤] Docs: README.md 수정 반영
  README.md
  src/pages/Cart/components/ContentsContainer/ContentsCart/container/SelectContainer.js
Labels: merge 요청
